# Generated by Django 5.1.3 on 2025-03-18 23:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Airport Name')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('country', models.CharField(max_length=100, verbose_name='Country')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Airport Code (IATA/ICAO)')),
            ],
            options={
                'verbose_name': 'Airport',
                'verbose_name_plural': 'Airports',
                'ordering': ['city', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=20, unique=True, verbose_name='Flight Number')),
                ('flight_name', models.CharField(max_length=100, verbose_name='Flight Name')),
                ('date', models.DateField(verbose_name='Flight Date')),
                ('departure_time', models.TimeField(blank=True, null=True, verbose_name='Departure Time')),
                ('arrival_time', models.TimeField(blank=True, null=True, verbose_name='Arrival Time')),
                ('available_seats', models.PositiveIntegerField(default=50, verbose_name='Available Seats')),
                ('economy_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Economy Class Price')),
                ('business_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Business Class Price')),
                ('first_class_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='First Class Price')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('destination_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arriving_flights', to='AirLine.airport', verbose_name='Destination Airport')),
                ('source_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departing_flights', to='AirLine.airport', verbose_name='Source Airport')),
            ],
            options={
                'verbose_name': 'Flight',
                'verbose_name_plural': 'Flights',
                'ordering': ['date', 'departure_time'],
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('nid', models.CharField(max_length=20)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger_name', models.CharField(max_length=100, verbose_name='Passenger Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('contact_phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Contact Phone')),
                ('ticket_class', models.CharField(choices=[('Economy', 'Economy'), ('Business', 'Business'), ('First', 'First')], max_length=20, verbose_name='Ticket Class')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ticket Price')),
                ('booked_at', models.DateTimeField(auto_now_add=True, verbose_name='Booked At')),
                ('booking_reference', models.CharField(max_length=20, verbose_name='Booking Reference')),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Pending', max_length=20, verbose_name='Payment Status')),
                ('status', models.CharField(choices=[('Pending', 'Pending Approval'), ('Approved', 'Approved'), ('Removed', 'Removed')], default='Pending', max_length=20, verbose_name='Approval Status')),
                ('seat_number', models.CharField(blank=True, max_length=5, null=True, verbose_name='Seat Number')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AirLine.flight', verbose_name='Flight')),
            ],
        ),
    ]
