# Generated by Django 5.1.3 on 2025-01-30 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AirLine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='booking_reference',
            field=models.CharField(default='Default_value', max_length=20, unique=True, verbose_name='Booking Reference'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Contact Phone'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Pending', max_length=20, verbose_name='Payment Status'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='flight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='AirLine.flight', verbose_name='Flight'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='is_sold',
            field=models.BooleanField(default=False, verbose_name='Is Sold'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='seat_number',
            field=models.CharField(max_length=5, unique=True, verbose_name='Seat Number'),
        ),
    ]
