# Generated by Django 5.1.3 on 2025-02-01 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AirLine', '0002_ticket_booking_reference_ticket_contact_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='seat',
        ),
        migrations.DeleteModel(
            name='Seat',
        ),
    ]
