# Generated by Django 5.1.3 on 2025-02-01 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AirLine', '0003_remove_ticket_seat_delete_seat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending Approval'), ('Approved', 'Approved'), ('Removed', 'Removed')], default='Pending', max_length=20, verbose_name='Approval Status'),
        ),
    ]
