# Generated by Django 5.1.3 on 2025-02-08 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AirLine', '0004_remove_ticket_is_approved_ticket_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='name',
            field=models.CharField(default='null', max_length=100, verbose_name='Flight Name'),
            preserve_default=False,
        ),
    ]
