# Generated by Django 5.1.3 on 2025-02-08 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AirLine', '0005_flight_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='name',
        ),
    ]
