# Generated by Django 5.1.3 on 2025-02-11 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AirLine', '0007_flight_flight_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='seat_number',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Seat Number'),
        ),
    ]
