# Generated by Django 5.1.3 on 2025-02-13 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AirLine', '0008_ticket_seat_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='booking_reference',
            field=models.CharField(max_length=20, verbose_name='Booking Reference'),
        ),
    ]
